version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.dockerfile
    restart: always
    ports:
      - '3000:3000'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      API_URL: http://backend:80/

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
    restart: always
    ports:
      - '8080:80'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_ADDRESS: :80
      CONTEXT_TIMEOUT: 10
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: admin
      DB_PASS: password
      DB_NAME: song-match
      ACCESS_TOKEN_EXPIRY_HOUR: 1
      REFRESH_TOKEN_EXPIRY_HOUR: 1
      ACCESS_TOKEN_SECRET: supersecrettoken
      REFRESH_TOKEN_SECRET: ultrasupersecrettoken

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - '27017:27017'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_DATABASE: song-match
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - '5672:5672'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
